# Generated by Django 3.2.5 on 2022-06-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0003_auto_20220619_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
